env:
  global:
    - secure: foCWstS0a9MaTDl6NaxyfX/gRXd1eH9D2sZATEQfn02jkLpiuCnFqOvJ7lOlDmBY0xV/X6zmK/XLiO3FiPshslnCdWnmRx+l9tJ0msLfR9z7c0g6tfaa1tlTh/psgi7OcENo8Bcc79G1zf5KlPg6+JELDbwHV2kny5US8vO0+Bigz8qht37FeTKF7o75vwTylZat56xkv9N3zABeLiU6eruZi6r9rQ2lE9pGSJvQvMhPhd+LCmDLWWb5pFXnjWTkd8ftl8n0XtmPoCqpOVorgNQX4ZeejsgXGE9kv/DE0ORAx5v9KHd2o2iFt2EA7fhTz0aWRA0g6N5UJNl11S39Q7QsFOCrQXIOF8Aib77jujwiidWVZnZxad1wA1YE3SgqJSSb/+B+C1FHaRPvFo+EV8PZ3DqB1KtMPd56XVOl3v/tD+q5jZQn7/UVYg9ZGIpmOoh3Mf9dQ/ci8kEcbVJ27+FwpSm/pC2c+5mQPn2XtkT9KSuunKKTeVrZPlZyYLb58zkUqgszpLMaAja7NGhnyFbnVrjhbkIHqLd+BiFEEfBdIQ1deWS7sVQ7GmhnFDJV/+3w+PPi44++vAw0SgxrHTWA9NOfONctqQbn5/UyzILKnBzpAMDcwaYezcDXA5RY8mpOMdCdcJ+S0yV7e4xb5rx+nX3auF8sLSRFZumqxLo=
    - secure: Jyy6VEg3fZ9vCje5xRRlGYGTL1Uf2WfhFBk0A3qMFUiYTxAha6oCAFs00PVwrZFfv6i3S3OFCPhuIVtg49Vya/Tzp3olalR261Yin1LoyeOJd9TzzfHnG/J/jG8wjreUOlMtmDSiiTmqTkw/gWSdfbSZ1oPGfGLb0VTb6fb9bmnSA4N0+UK3NMGEjnoSVbJif4DDrASDzSAldALgtvDDj/ehC/FocBw/bCA8OiwP+X4ZUqgBCMmRQbuuRIZq8/smIx44nu3RQmXAjmJJqe1O43gESk7eogBMSdaQmtlkLp5dDQIVMpU2SaouefMZm7FYUlj4cGvOdGdKZ24PP3PdKlIaworDbUKg3NbMxi3eTpPvK42NEE7emjLzxpGaKwTvwCsSV1Vva8XH1PJVNAua9nePVj+Zr5OA/CBdKO68OJsdejgDqzgSotmRNeNP+sHtKdw49NQ6QJysWKRC8GKqQPrvWyZdZgKcD40LV18968KjMeu3FJCNzDHh7GxqX6GmUfUnA8bES12Cg8X4JIeDwqixJ8ExzjIzaWr663HFEkntryY4YNnDS2cWWHoRrKIgAvj93RhbCHElBzu/VNsbTnZicbRkHbapu5ahpw+vjAQCAF0jcAPHuojgWo1l3XDQN6Y6NysoQ/oVHHfdP235CLKVpn2kt7x8l9x9ARpxb9s=

sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=mjelen/roadshow-content
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker push $REPO
